/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_sxh_androidjni_JNI */

#ifndef _Included_cn_sxh_androidjni_JNI
#define _Included_cn_sxh_androidjni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_sxh_androidjni_JNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_sxh_androidjni_JNI_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
